export const ACTION_NAVIGATE_LOGIN = 'ACTION_NAVIGATE_LOGIN';
export const ACTION_NAVIGATE_SIGNUP = 'ACTION_NAVIGATE_SIGNUP';

// LoginView
export const ACTION_LOGGING_USER = 'ACTION_LOGGING_USER';
export const ACTION_LOGIN_USER_SUCCESS = 'ACTION_LOGIN_USER_SUCCESS';
export const ACTION_LOGIN_USER_FAILURE = 'ACTION_LOGIN_USER_FAILURE';
export const PREF_USER = 'PREF_USER';
