//Loaders
export const ACTION_SHOW_LOADER = 'SHOW_LOADER';
export const ACTION_HIDE_LOADER = 'HIDE_LOADER';

// LoginView
export const ACTION_LOGIN_USER_SUCCESS = 'ACTION_LOGIN_USER_SUCCESS';
export const PREF_USER = 'PREF_USER';

//Signup
export const ACTION_SIGNUP_SUCCESS = 'ACTION_SIGNUP_SUCCESS';
